basePath: /
definitions:
  main.checkContractStandardResponse:
    properties:
      address:
        type: string
      standard:
        type: string
    type: object
  main.checkVerificationStatusResponse:
    properties:
      address:
        type: string
      verified:
        type: boolean
    type: object
  main.newContractResponse:
    properties:
      address:
        type: string
      block:
        type: integer
      standard:
        type: string
      transaction:
        type: string
      verified:
        type: boolean
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Check if the contract at the given Ethereum address is an ERC-20 or
    ERC-721 contract, and whether it has been verified on Etherscan.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ethereum Contract Checker API
  version: "1.0"
paths:
  /checkContractStandard/{address}:
    get:
      consumes:
      - application/json
      description: Check if the contract at the given Ethereum address is an ERC-20
        or ERC-721 contract
      operationId: checkContractStandard
      parameters:
      - description: Ethereum address of the contract to check Standard
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: Contract Address
              type: string
          schema:
            $ref: '#/definitions/main.checkContractStandardResponse'
      summary: Check the contract standard for an Ethereum address
  /checkVerificationStatus/{address}:
    get:
      consumes:
      - application/json
      description: Check if the contract has been verified on Etherscan.
      operationId: checkVerificationStatus-contract
      parameters:
      - description: Ethereum address of the contract to checkVerificationStatus
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: Contract Address
              type: string
          schema:
            $ref: '#/definitions/main.checkVerificationStatusResponse'
      summary: Check the contract verification status for an Ethereum address
  /getContracts/{startBlock}/{endBlock}:
    get:
      consumes:
      - application/json
      description: Returns a list of new contracts deployed between a start and end
        block, along with their verification status, standard (ERC-20 or ERC-721),
        and transaction details.
      parameters:
      - description: Start block
        in: path
        name: startBlock
        required: true
        type: string
      - description: End block
        in: path
        name: endBlock
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.newContractResponse'
            type: array
      summary: Get the new contracts deployed between a start and end block
      tags:
      - Contracts
swagger: "2.0"
