basePath: /
definitions:
  main.checkContractTypeResponse:
    properties:
      address:
        type: string
      standard:
        type: string
    type: object
  main.checkVerificationStatusResponse:
    properties:
      address:
        type: string
      verified:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Check if the contract at the given Ethereum address is an ERC-20 or
    ERC-721 contract, and whether it has been verified on Etherscan.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ethereum Contract Checker API
  version: "1.0"
paths:
  /checkContractType/{address}:
    get:
      consumes:
      - application/json
      description: Check if the contract at the given Ethereum address is an ERC-20
        or ERC-721 contract
      operationId: checkContractType-contract
      parameters:
      - description: Ethereum address of the contract to checkContractType
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: Contract Address
              type: string
          schema:
            $ref: '#/definitions/main.checkContractTypeResponse'
      summary: Check the contract type
  /checkVerificationStatus/{address}:
    get:
      consumes:
      - application/json
      description: Check if the contract has been verified on Etherscan.
      operationId: checkVerificationStatus-contract
      parameters:
      - description: Ethereum address of the contract to checkVerificationStatus
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: Contract Address
              type: string
          schema:
            $ref: '#/definitions/main.checkVerificationStatusResponse'
      summary: Check the contract verification status for an Ethereum address
swagger: "2.0"
